### ISSUE TITLE
Chybějící soubor

### ISSUE THREAD

**Issue by znelkytv** [petrj/OnlineTelevizor#9]
V souboru chybí aplikace, nebyla nalezena nebo nebyla přiložena.

**Comment by petrj** [comment]
Vůbec nerozumím. Který soubor má chybět?
I don't understand. What file is missing?

**Comment by znelkytv** [comment]
Chybí aplikace, nevím, jak ji zapnout, nikde jsem nenašel soubor s aplikací

Dne po 17. 4. 2023 14:50 uživatel Petr ***@***.***> napsal:

**Comment by petrj** [comment]
Odkaz na aplikaci v Google Play je dole v popisu. APK balíček pro Android a build pro UWP je v sekci Releases. 

https://play.google.com/store/apps/details?id=net.petrjanousek.OnlineTelevizor
https://github.com/petrj/OnlineTelevizor/releases
